In [53]:
import generators
from matplotlib import pyplot as plt 
import torch
import torch.nn.functional as F
from torch import nn
import numpy as np
import pandas as pd 
from importlib import reload
reload(generators)
None
from typing import List, Tuple
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SequentialSampler, RandomSampler
import torchvision.transforms as T
from scipy.optimize import linear_sum_assignment

In [64]:
X = torch.tensor([
    [1,1,0,0], # 0
    [1,1,1,0], # 0
    [0,0,0,1], # 1
    [0,1,1,1], # 1
    [1,0,0,0], # 0
    [1,0,1,0], # 0
    [1,0,0,0], # 0
    [0,1,0,1], # 1
], dtype=torch.float32)

y = torch.tensor([0,0,1,1,0,0,0,1], dtype=torch.float32).reshape(-1,1)

# W = torch.randn(4,1)*100
W = torch.tensor([0,0,0,1], dtype=torch.float32).reshape(-1,1)
W.requires_grad = True

In [76]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(params=[W], lr=0.00001)

In [77]:
W

tensor([[-3.0070e-04],
        [ 6.2413e-04],
        [ 4.4616e-05],
        [ 9.9917e-01]], requires_grad=True)

In [78]:
for epoch in range(100000):
    pred = X@W
    loss = criterion(pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
print(loss)
    
    
with torch.no_grad():
    print(X@W)
    print((X@W).round().abs())

tensor(1.4984e-07, grad_fn=<MseLossBackward>)
tensor([[ 2.9510e-04],
        [ 3.5424e-04],
        [ 9.9917e-01],
        [ 9.9979e-01],
        [-2.6820e-04],
        [-2.0907e-04],
        [-2.6820e-04],
        [ 9.9974e-01]])
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]])
